/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdArmrecording: typeof import('@kalimahapps/vue-icons/ad')['AdArmrecording']
    BsWindow: typeof import('@kalimahapps/vue-icons/bs')['BsWindow']
    BxWindowClose: typeof import('@kalimahapps/vue-icons/bx')['BxWindowClose']
    FaRegWindowMaximize: typeof import('@kalimahapps/vue-icons/fa')['FaRegWindowMaximize']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
